name: IllegalStackTrans
version: "3.0.0 Net Minecraft Server Mixins"
api-version: 1.21
folia-supported: true
description: 修复了一些仍然存在于 Minecraft原版 的特性。插件原作者dNiym和Loving11ish，本插件是对 IllagalStack 插件的扩展和中文翻译，支持Mixin的版本
authors: [dNiym, Loving11ish, MFS-Mysterious Frame Slot]
softdepend: [Magic, Factions, NBTAPI, ProtocolLib, Slimefun, CraftingStore, DynamicShop, ClueScrolls, mcMMO, JetsMinions, SmartInvs, FactionsX]
load-before: [MythicDrops]

# Paper 插件自动加载 Mixin 配置
mixins:
  - mixins.json

main: main.java.me.dniym.IllegalStack

commands:
  tpa-player:
    description: TPA 传送系统
    usage: /tpa-player <access|deny|to|setting> ...
  istack:
    description: 允许使用 /istack 指令调试该插件。
    permission: illegalstack.help
    usage: "Usage: /istack"
  admin:
    description: IllagalStackTrans Extra Commands
    usage: /admin ...
    
permissions:
  illegalstack.admin:
    description: 允许玩家使用 /istack protections 命令。
    default: op
  illegalstack.help:
    description: 允许拥有此权限的玩家使用 /istack 命令。
    default: op
  illegalstack.notify:
    description: 允许拥有此权限的玩家接收游戏内的违规通知并传送到相应地点。
    default: op
  illegalstack.enchantbypass:
    description: 允许拥有此权限的玩家使用突破原版附魔限制的物品。
    default: false
  illegalstack.removeitemsoftypebypass:
    description: 允许拥有此权限的玩家绕过移除特定类型物品的检查。
    default: false
  illegalstack.overstack:
    description: 允许拥有此权限的玩家使用此列表中超过原版堆叠数量的物品。
    default: true
  illegalstack.serverchat:
    description: 此权限已弃用，原功能已合并至 /admin chat。
    default: op
