name: IllegalStackTrans
version: "3.0.0"
api-version: 1.21
folia-supported: true
description: IllagalStack 的超级修改版
authors: [dNiym, Loving11ish, MFS-Mysterious Frame Slot]
softdepend: [Magic, Factions, NBTAPI, ProtocolLib, Slimefun, CraftingStore, DynamicShop, ClueScrolls, mcMMO, JetsMinions, SmartInvs, FactionsX]
load-before: [MythicDrops]

main: main.java.me.dniym.IllegalStack
